version: '3'

x-services:
  develop: &development
    network_mode: "host"
    hostname: ${HOSTNAME}
    build: &build
      context: .
      args:
        HOSTUSER: "usc"
        HOSTGROUP: "usc"
        HOSTUID: "1000"
        HOSTGID: "1000"
        LANG: "de_DE.UTF-8"
        SHELL: "/usr/bin/zsh"
        TZ: "Europe/Berlin"
    volumes:
      - "~:/home/usc"
      - "/run/media/usc/:/run/media/usc/"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

services:
  go-development:
    <<: *development
    build:
      <<: *build
      dockerfile: "Dockerfile.go"
  rust-development:
    <<: *development
    build:
      <<: *build
      dockerfile: "Dockerfile.rust.stable"
  zig-development:
    <<: *development
    build:
      <<: *build
      dockerfile: "Dockerfile.zig"
